---
name: crime_patterns
channels:
  - conda-forge
  - nodefaults
  - anaconda

dependencies:
  - numpy
  - xarray
  - netcdf4
  - conda-lock
  - ipykernel
  - jupyterlab
  - pandas
  - geopandas
  - pysal
  - splot
  - scikit-learn
  - contextily
  - rasterio
  - pointpats
  - pdbpp
  - pip >=21.1
  - plotly>=5.13.0
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-graphviz
  - python=3.9
  - pyyaml
  - setuptools_scm
  - statsmodels
  - toml
  - pip:
      - -e .
      - kaleido
