name: Setup-Miniconda

on:
  push:
    branches:
    - 'github_actions'
  pull_request:
    branches:
    - '*'

jobs:
  run-tests:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run pytest
        shell: bash -l {0}
        run: |
          conda install pytest
          pytest -vv